# Generated by Django 3.2.16 on 2022-11-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180616_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
